development:
  adapter: postgresql
  encoding: unicode
  database: sinatra100
  pool: 2
  
production:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 2
  username: your_username
  password: your_password
